integration: add new nsci network
opiproject/opi-poc pull request #276
Opened 2022-08-05 20:03 UTC by glimchb

HOST-NCSI network is to connect internally HOST and HOST-BMC
XPU-NCSI network is to connect internally xPU and XPU-BMC

Fixes #268

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

2022-08-05 20:36 UTC, glimchb commented
all good now
```
xpu-telegraf_1            | redfish_thermal_temperatures,address=xpu-bmc-ssh,health=OK,host=xpu-cpu,member_id=0,name=CPU1\ Temp,rack=WEB43,row=North,source=web483,state=Enabled reading_celsius=41,upper_threshold_critical=45,upper_threshold_fatal=48 1659731680000000000
xpu-telegraf_1            | redfish_thermal_temperatures,address=xpu-bmc-ssh,host=xpu-cpu,member_id=1,name=CPU2\ Temp,rack=WEB43,row=North,source=web483,state=Disabled upper_threshold_critical=45,upper_threshold_fatal=48 1659731680000000000
xpu-telegraf_1            | redfish_thermal_temperatures,address=xpu-bmc-ssh,health=OK,host=xpu-cpu,member_id=2,name=Chassis\ Intake\ Temp,rack=WEB43,row=North,source=web483,state=Enabled upper_threshold_fatal=50,lower_threshold_critical=5,lower_threshold_fatal=0,reading_celsius=25,upper_threshold_critical=40 1659731680000000000
xpu-telegraf_1            | redfish_thermal_fans,address=xpu-bmc-ssh,health=OK,host=xpu-cpu,member_id=0,name=BaseBoard\ System\ Fan,rack=WEB43,row=North,source=web483,state=Enabled lower_threshold_fatal=0i,reading_rpm=2100i 1659731680000000000
xpu-telegraf_1            | redfish_thermal_fans,address=xpu-bmc-ssh,health=OK,host=xpu-cpu,member_id=1,name=BaseBoard\ System\ Fan\ Backup,rack=WEB43,row=North,source=web483,state=Enabled lower_threshold_fatal=0i,reading_rpm=2050i 1659731680000000000
xpu-telegraf_1            | redfish_power_powersupplies,address=xpu-bmc-ssh,health=Warning,host=xpu-cpu,member_id=0,name=Power\ Supply\ Bay,rack=WEB43,row=North,source=web483,state=Enabled line_input_voltage=120,last_power_output_watts=325,power_capacity_watts=800 1659731680000000000
xpu-telegraf_1            | redfish_power_voltages,address=xpu-bmc-ssh,health=OK,host=xpu-cpu,member_id=0,name=VRM1\ Voltage,rack=WEB43,row=North,source=web483,state=Enabled lower_threshold_fatal=10,reading_volts=12,upper_threshold_critical=13,upper_threshold_fatal=15,lower_threshold_critical=11 1659731680000000000
xpu-telegraf_1            | redfish_power_voltages,address=xpu-bmc-ssh,health=OK,host=xpu-cpu,member_id=1,name=VRM2\ Voltage,rack=WEB43,row=North,source=web483,state=Enabled reading_volts=5,upper_threshold_critical=7,lower_threshold_critical=4.5 1659731680000000000
```
and
```
host-telegraf_1           | redfish_thermal_temperatures,address=host-bmc-ssh,health=OK,host=host-cpu,member_id=0,name=CPU1\ Temp,rack=WEB43,row=North,source=web483,state=Enabled reading_celsius=41,upper_threshold_critical=45,upper_threshold_fatal=48 1659731680000000000
host-telegraf_1           | redfish_thermal_temperatures,address=host-bmc-ssh,host=host-cpu,member_id=1,name=CPU2\ Temp,rack=WEB43,row=North,source=web483,state=Disabled upper_threshold_critical=45,upper_threshold_fatal=48 1659731680000000000
host-telegraf_1           | redfish_thermal_temperatures,address=host-bmc-ssh,health=OK,host=host-cpu,member_id=2,name=Chassis\ Intake\ Temp,rack=WEB43,row=North,source=web483,state=Enabled reading_celsius=25,upper_threshold_critical=40,upper_threshold_fatal=50,lower_threshold_critical=5,lower_threshold_fatal=0 1659731680000000000
host-telegraf_1           | redfish_thermal_fans,address=host-bmc-ssh,health=OK,host=host-cpu,member_id=0,name=BaseBoard\ System\ Fan,rack=WEB43,row=North,source=web483,state=Enabled lower_threshold_fatal=0i,reading_rpm=2100i 1659731680000000000
host-telegraf_1           | redfish_thermal_fans,address=host-bmc-ssh,health=OK,host=host-cpu,member_id=1,name=BaseBoard\ System\ Fan\ Backup,rack=WEB43,row=North,source=web483,state=Enabled lower_threshold_fatal=0i,reading_rpm=2050i 1659731680000000000
host-telegraf_1           | redfish_power_powersupplies,address=host-bmc-ssh,health=Warning,host=host-cpu,member_id=0,name=Power\ Supply\ Bay,rack=WEB43,row=North,source=web483,state=Enabled power_capacity_watts=800,line_input_voltage=120,last_power_output_watts=325 1659731680000000000
host-telegraf_1           | redfish_power_voltages,address=host-bmc-ssh,health=OK,host=host-cpu,member_id=0,name=VRM1\ Voltage,rack=WEB43,row=North,source=web483,state=Enabled reading_volts=12,upper_threshold_critical=13,upper_threshold_fatal=15,lower_threshold_critical=11,lower_threshold_fatal=10 1659731680000000000
host-telegraf_1           | redfish_power_voltages,address=host-bmc-ssh,health=OK,host=host-cpu,member_id=1,name=VRM2\ Voltage,rack=WEB43,row=North,source=web483,state=Enabled reading_volts=5,upper_threshold_critical=7,lower_threshold_critical=4.5 1659731680000000000
```

2022-08-08 14:04 UTC, mestery requested changes
Please update the diagram before we merge his. Otherwise looks great!

2022-08-08 15:08 UTC, glimchb commented
> Please update the diagram before we merge his. Otherwise looks great!

updated

2022-08-08 15:16 UTC, mestery approved these changes
Most wonderful, thank you!

2022-08-08 15:16 UTC, merged