lab goals and requirements update to PR#359
opiproject/opi-poc pull request #540
Opened 2022-12-15 08:14 UTC by mgheorghe

Signed-off-by: Mircea Dan Gheorghe <mircea-dan.gheorghe@keysight.com>

2023-01-23 14:09 UTC, seroyer commented
@mgheorghe #558 was merged which fixes the YAMLlint issue.  If you push a change or rebase, that should fix it.

2023-01-27 16:27 UTC, pdp2shirts commented
@opiproject/opi-maintainers we reviewed this PR in lab discussion call and we ask that this be merged and future changes can be new PR

2023-01-27 19:39 UTC, glimchb requested changes
what about original file https://github.com/opiproject/opi-poc/blob/main/lab/lab_requirement.md ?

should you remove it as part of this PR ? rename it ?

2023-01-31 13:42 UTC, glimchb approved these changes
lgtm, please squash and fix DCO and we can merge it

2023-02-02 02:33 UTC, closed without merging