poc for opi testing suite
opiproject/opi-poc pull request #675
Opened 2023-03-02 08:33 UTC by mgheorghe

includes:

- multiple scenarios of traffic sources and destinations residing on the dpu host or on a separate server
- automated python scripts
- pytest framework integration
- opi apis for ipsec
- netmiko usage for remote commands to complement opi apis
- testbed file
- a proposal for how passwords can be kept secret

2023-03-02 23:47 UTC, glimchb requested changes
looks good. few comments inside

2023-03-02 23:49 UTC, mgheorghe commented on demos/tgen/ipsec_pb2.py
> +# Generated by the protocol buffer compiler.  DO NOT EDIT!
pydpu usage was in plan but did not had time to make it work properly , i can work on this and update the PR

2023-03-02 23:49 UTC, mgheorghe commented on demos/tgen/ipsec_pb2_grpc.py
> +import grpc
pydpu usage was in plan but did not had time to make it work properly , i can work on this and update the PR

2023-03-02 23:51 UTC, mgheorghe commented on demos/tgen/test_tgen_with_ipsec_demo.py
> +    command = 'docker run --rm --network host --mount src=/var/run,target=/var/run,type=bind --name opi-strongswan-bridge -d ghcr.io/opiproject/opi-strongswan-bridge:main /opi-vici-bridge -port=50151
it was only 1 container , 1 less file to transfer , docker compose could work also , ideally an OPI enabled DPU will have the OPI API endpoint running on the DPU and not need the test to start it.

2023-03-02 23:54 UTC, mgheorghe commented on demos/tgen/test_tgen_with_ipsec_demo.py
> +    print('connecting to opi')
I'm working on some pydpu proposals but that PR is not ready yet.

2023-03-09 18:17 UTC, mgheorghe commented on demos/tgen/ipsec_pb2.py
> +# Generated by the protocol buffer compiler.  DO NOT EDIT!
filex removed

2023-03-09 18:18 UTC, mgheorghe commented on demos/tgen/ipsec_pb2_grpc.py
> +import grpc
files removed

2023-03-09 18:21 UTC, mgheorghe commented on demos/tgen/test_tgen_with_ipsec_demo.py
> +    command = 'docker run --rm --network host --mount src=/var/run,target=/var/run,type=bind --name opi-strongswan-bridge -d ghcr.io/opiproject/opi-strongswan-bridge:main /opi-vici-bridge -port=50151
strongswan in this case it already exists and running on the dpu.
i'll keep the docker run for this scenario

2023-03-09 19:24 UTC, glimchb commented
@mgheorghe can you please `git rebase` instead of merge, I have trouble reviewing all those changes with 19 commits in them...

2023-03-09 19:25 UTC, glimchb approved these changes
lgtm, but needs rebase first

2023-03-10 00:16 UTC, mgheorghe commented
it's a combination of hitting the update button and doing the dco signing (happens to me only in this project) 
i'll fix it from the git command line that always does the tricks although is more convenient to just click the button :|
![image](https://user-images.githubusercontent.com/32941360/224190123-0aba16e2-b13d-4839-b414-6f84a33bef92.png)

2023-03-10 03:31 UTC, merged